### ISSUE TITLE
User can start the stop watch.

### ISSUE THREAD

**Issue by ronperris** [occs/stop-watch#1]
### Tasks
- [x] Create start button in html.
- [x] Create CSS for button.
- [x] Create CSS for watch.
- [x] Create function for rendering watch.
- [x] Create function for starting watch.
- [x] Register event listener on start button.

**Comment by ronperris** [comment]
![screen shot 2018-02-27 at 12 56 42 pm](https://user-images.githubusercontent.com/963451/36754418-c3291626-1bbd-11e8-81a7-8899193c5bb2.png)
